### PR TITLE
Changes to Repeat and Reverse

### PR DESCRIPTION
**Pull request by kiraknowsbest**
### Description

Repeat: Removed while loop, used repeat method of String.prototype to improve readability
Reverse: Changed function to increase time complexity from O(3n) to O(n)

### Check List

- [X] All test passed
- [ ] Added test to ensure correctness

### CODE REVIEW

**Comment by panzerdp** [comment]
Hi @kiraknowsbest!

Thanks for the pull request.

However:
* `repeat()` method is a part of ES2015 specification. Because the library targets ES5, it would require to include a polyfill for it: and I don't want that. The current `while () {...}` implementation does not create this dependency.
* `reverse()`: in some situations the proposed code may perform faster. But I'm ok with the current implementation, since I like the functional programming approaches. Constants in time complexity are skipped θ(3n) = θ(n) anyway, and I am not interested in micro-optimizations.

Thanks for your time.

**Comment by kiraknowsbest** [comment]
Hi,

I respect you decision fully. I understand the reasoning for not using
repeat(), and your preference for functional programming is completely
understandable as well. Very interesting library, nice work!

**Comment by pwolaq** [comment]
How about using better version of `repeat` like the one here: http://www.2ality.com/2014/01/efficient-string-repeat.html

**Comment by panzerdp** [comment]
@pwolaq Actually this algorithm is implemented in Voca's `repeat()` :repeat:

**Comment by kiraknowsbest** [comment]
Yeah, it seems this algorithm is a bit more witty than it appears!

**Comment by panzerdp** [comment]
Thanks @kiraknowsbest!
If you have suggestions, feel free to open issues for discussion.

**Pull request closed without merging**
